// GENERATED by tools/build_coverage.js — do not hand-edit. Re-run after any leads re-bake.
window.MACO_COVERAGE={
 "miamicw": {
  "label": "Miami-Dade",
  "county": "Miami-Dade",
  "leads": 3000,
  "submarkets": 41,
  "snapshot": "2026-07-20",
  "freshness": "dated",
  "asOf": "2026-07-20",
  "roll": "Miami-Dade PA (PaGISView)"
 },
 "broward": {
  "label": "Broward",
  "county": "Broward",
  "leads": 600,
  "submarkets": 16,
  "snapshot": "2026-07-29",
  "freshness": "dated",
  "asOf": "2026-07-29",
  "roll": "2025 roll"
 },
 "lee": {
  "label": "Lee",
  "county": "Lee",
  "leads": 600,
  "submarkets": 15,
  "snapshot": "2026-07-28",
  "freshness": "dated",
  "asOf": "2026-07-28",
  "roll": "2025 roll"
 },
 "collier": {
  "label": "Collier",
  "county": "Collier",
  "leads": 600,
  "submarkets": 7,
  "snapshot": "2025 roll",
  "freshness": "annual",
  "asOf": "2025 roll",
  "roll": ""
 },
 "polk": {
  "label": "Polk",
  "county": "Polk",
  "leads": 867,
  "submarkets": 8,
  "snapshot": "2026-07-01",
  "freshness": "dated",
  "asOf": "2026-07-01",
  "roll": ""
 },
 "lake": {
  "label": "Lake",
  "county": "Lake",
  "leads": 120,
  "submarkets": 1,
  "snapshot": "2026-07-11",
  "freshness": "dated",
  "asOf": "2026-07-11",
  "roll": ""
 }
};
