// Emits coverage.js — the single source of truth for what the PUBLIC pages claim about
// each market's freshness and size. Jul 2026 audit: index.html and markets.html hard-coded
// "Rolling refresh" for every county while Broward and Collier were still on a 2025 roll.
// Hand-written dates re-rot after every refresh, so the marketing pages now read this file.
//
// Run after any leads re-bake:  node tools/build_coverage.js
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const MARKETS = [
  { key: 'miamicw', file: 'miami-leads.js',   global: 'MIAMI_META',   label: 'Miami-Dade' },
  { key: 'broward', file: 'broward-leads.js', global: 'BROWARD_META', label: 'Broward' },
  { key: 'lee',     file: 'lee-leads.js',     global: 'LEE_META',     label: 'Lee' },
  { key: 'collier', file: 'collier-leads.js', global: 'COLLIER_META', label: 'Collier' },
  { key: 'polk',    file: 'polk-leads.js',    global: 'POLK_META',    label: 'Polk' },
  { key: 'lake',    file: 'lake-leads.js',    global: 'LAKE_META',    label: 'Lake' },
];

// A bare "2025 roll" (or any non-ISO string) is an annual tax roll, not a dated refresh.
// Label it as such rather than letting it pass for a recent pull.
function describe(snapshot) {
  if (/^\d{4}-\d{2}-\d{2}$/.test(snapshot || '')) return { kind: 'dated', asOf: snapshot };
  return { kind: 'annual', asOf: snapshot || 'unknown' };
}

const out = {};
let failed = 0;
for (const m of MARKETS) {
  const p = path.join(ROOT, m.file);
  if (!fs.existsSync(p)) { console.log(`MISSING ${m.file}`); failed++; continue; }
  const sandbox = { window: {} };
  try {
    vm.createContext(sandbox);
    new vm.Script(fs.readFileSync(p, 'utf8'), { filename: m.file }).runInContext(sandbox);
  } catch (e) {
    console.log(`FAILED to load ${m.file}: ${e.message}`);
    failed++; continue;
  }
  const meta = sandbox.window[m.global];
  if (!meta) { console.log(`NO ${m.global} in ${m.file}`); failed++; continue; }
  const d = describe(meta.snapshot);
  out[m.key] = {
    label: m.label,
    county: meta.county || m.label,
    leads: meta.count || 0,
    submarkets: (meta.markets || []).length,
    snapshot: meta.snapshot || '',
    freshness: d.kind,
    asOf: d.asOf,
    roll: meta.roll || '',
  };
  console.log(`${m.label.padEnd(12)} ${String(out[m.key].leads).padStart(5)} leads · ${d.kind === 'dated' ? 'refreshed ' + d.asOf : 'annual ' + d.asOf}`);
}

const banner = '// GENERATED by tools/build_coverage.js — do not hand-edit. Re-run after any leads re-bake.\n';
fs.writeFileSync(path.join(ROOT, 'coverage.js'), banner + 'window.MACO_COVERAGE=' + JSON.stringify(out, null, 1) + ';\n');
console.log(`\ncoverage.js written (${Object.keys(out).length} markets, ${failed} failed).`);
process.exit(failed ? 1 : 0);
